version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/peer_learning_system
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=20030107
    depends_on:
      - db

  frontend:
    build: ./front/Peer-Assessment-System
    ports:
      - "9527:9527"

  db:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=peer_learning_system
      - MYSQL_ROOT_PASSWORD=20030107
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/peer_system.sql:/docker-entrypoint-initdb.d/init.sql

  redis: # 新增的Redis服务
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db-data:

